### ISSUE TITLE
C2724 and C2725 spellings/forms

### ISSUE THREAD

**Issue by ctschroeder** [KELLIA/dictionary#136] opened 2020-08-13 23:00 UTC
Are C2724 and C2725 deliberately spelled ⲛⲟϭⲛⲟϭ rather than ⲛⲟϭⲛⲉϭ?  ⲛⲟϭⲛⲉϭ is the lemma in Crum, and I think is the traditional form of the lemma.  If this is not deliberate, can we change it?  If it is deliberate, can we add ⲛⲟϭⲛⲉϭ so it can be found in search?  Thank you.
http://coptic-dictionary.org/entry.cgi?tla=C2724
http://coptic-dictionary.org/entry.cgi?tla=C2725

**Comment by phoenix-mossimo** [comment] 2020-08-19 15:55
Duplicate of #80

This bug has been corrected with V1.2 (see the testserver), but the new dataset has not been uploaded to CDO yet.

**Closed by phoenix-mossimo** 2020-08-19 15:55 UTC
