### ISSUE TITLE
Typo: C117: CS137: Unkontollierbarkeit

### ISSUE THREAD

**Issue by simondschweitzer** [KELLIA/dictionary#134] opened 2020-08-12 13:47 UTC
This should be 'Unkontrollierbarkeit'.

**Comment by phoenix-mossimo** [comment] 2020-08-19 15:57
True, an eye of a eagle you have :-). Won't make it in the V1.2, but hopefully in the next one.

**Comment by m-linssen** [comment] 2021-02-10 10:28
Duplicate of #154

**Comment by dwerning** [comment] 2023-05-13 06:46
Done, checked.

**Closed by dwerning** 2023-05-13 06:46 UTC
