### ISSUE TITLE
Not all search results displayed 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#1] opened 2016-08-17 08:55 UTC
Steps to reproduce: 
Type in "ⲉⲓⲣⲉ": "Search had 276 results - showing first 100" - the rest is not displayed, no buttons to go forward / backward

**Comment by amir-zeldes** [comment] 2016-08-22 13:57
I can change this easily, but it was actually intended as a feature, not a bug. If we don't have a limit on search results, you can search for .* and get all entries in the dictionary. This is potentially a burden on the browser, and definitely a way to download all entries for any user. 

If this is what you want, we can test browser load (should be possible on a modern-ish computer), and then it's just an issue of whether or not you want the underlying dataset to be easily downloadable. As far as I know, we still don't have a license for the underlying data, which is the main reason I haven't made the private repo containing the code for the Web app public. The code itself can be released fully open source (e.g. Apache 2.0) as far as I am concerned.

**Comment by phoenix-mossimo** [comment] 2016-08-23 08:21
Yes, you are right, this is matter of license and beyond my competence. Then we can at least restructure the display of search results, so that the basic meanings are shown first (see #2).

**Comment by amir-zeldes** [comment] 2016-10-11 18:48
@phoenix-mossimo - can I close this or is it really desired to display all entries? I think if it's for a human user, above 100 is probably not so useful - I can also make the limit higher than 100 though.

**Comment by phoenix-mossimo** [comment] 2016-10-24 12:29
@amir-zeldes: We have decided to use CC BY-SA 4.0 license for all TLA / CLL data. So there is no reason now not to display all search results. Could you just split them into chunks of 50 with the buttons "next", "previous" or provide a drop-down where the user can choose the amount displayed (20, 50, 100, all)?

**Comment by amir-zeldes** [comment] 2016-10-24 13:30
OK, that should be possible. I think pages of 50 or 100 results are pretty reasonable.

**Comment by phoenix-mossimo** [comment] 2017-09-13 14:27
The problem is still there: 
"You searched for '.*ϥ'
Search had 223 results - showing first 100". 

Strangely "Include related entries" has no such restriction: 
"Entries related to '.*ϥ'
181 Results".

**Comment by dwerning** [comment] 2019-05-31 06:49
IMO we need a scroll **forward/backward functionality**. This is how all pages like this work. (To me it is indeed more on the "bug" side.) Chunks of 50 or 100 make sense to me.

**Closed** 2019-06-18 09:35 UTC
Labels: bug, enhancement
