### ISSUE TITLE
Fix XML entry for "ⲣ ⲁⲡⲉ (ⲉϩⲣⲁⲓ ⲉϫⲛ-)" (was: entry displayed as NONE)

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#13] opened 2016-10-25 09:43 UTC
Search for "ⲣ ⲁⲡⲉ" - "rule" -> works. But one of its sub-entries (ⲣ ⲁⲡⲉ (ⲉϩⲣⲁⲓ ⲉϫⲛ-)) is displayed as NONE

**Comment by amir-zeldes** [comment] 2016-10-25 14:28
OK, I've fixed this manually, but the XML is irregular at this point and should be fixed: normally the <form> tag contains the form literally as a plain text child, here the form is only in the <gram> element. Only the preposition belongs there if I understand this right. As far as I can tell, this is the only case. Leaving this open as a reminder to fix the XML, please close once that's done for the next version.

**Comment by phoenix-mossimo** [comment] 2016-10-25 15:06
I did not quite get it. 
Form can be either in <form> tag directly (Sahidic) or in the subordinate <orth> tag (other dialects), in which case it is accompanied by <usg> tag. Your script reads this perfectly. 

But - there are some Sahidic forms, which were put into <orth> tag, without the accompanying <usg> information. Maybe this is a problem?

**Comment by amir-zeldes** [comment] 2016-10-26 15:55
No, the problem is how the form is included - compare the following two examples. This is the way most compound entries are organized, with the head word in the 'form' element:

```
        <entry type="compound">
          <form>ⲁⲗⲉ (ⲉϩⲣⲁⲓ)</form>
            <gramGrp>
              <pos>Vb.</pos>
              <gram type="collocPrep">ⲉϩⲣⲁⲓ</gram>
            </gramGrp>
          <sense>
            <ref type="Greek">προβαίνειν</ref>
            <cit type="translation" xml:lang="de">
              <quote>aufsteigen; älter werden</quote>
            </cit>
            <cit type="translation" xml:lang="en">
              <quote>mount up; ascend (in years)</quote>
            </cit>
            <cit type="translation" xml:lang="fr">
              <quote>monter; vieillir</quote>
            </cit>
            <cit>
              <bibl>CD 4ab</bibl>
            </cit>
          </sense>        
        </entry>
```

This is how r-ape (and only r-ape) is organized - note how the only place specifying orthography for the entry is in the gram element:

```
        <entry>
          <form type="compound">
            <gramGrp>
              <gram type="collocPrep">ⲣ ⲁⲡⲉ (ⲉϩⲣⲁⲓ) ⲉϫⲛ-</gram>
            </gramGrp>
          </form>
          <sense>
            <cit type="translation" xml:lang="de">
              <quote>herrschen über</quote>
            </cit>
            <cit type="translation" xml:lang="en">
              <quote>rule over</quote>
            </cit>
            <cit type="translation" xml:lang="fr">
              <quote>régner sur</quote>
            </cit>
            <cit>
            <bibl>KoptHWb 10</bibl>
            </cit>
          </sense>
        </entry>
```

Since only r-ape has this structure, it's sufficient to change this one entry to avoid the bug (I've already done it in the live instance, I just want the error not to recur in the next version of the XML)

**Comment by phoenix-mossimo** [comment] 2016-10-27 17:58
The code you posted for "r-ape" is definitely wrong - the orthographic form is missing. Mine looks like this: 
       <entry>
          <form type="compound">
            <orth>ⲣ ⲁⲡⲉ (ⲉϩⲣⲁⲓ ⲉϫⲛ-)</orth>
            <gramGrp>
              <pos>Vb.</pos>
              <gram type="collocPrep">ⲉϩⲣⲁⲓ ⲉϫⲛ-</gram>
            </gramGrp>
          </form>
          <sense>
            <cit type="translation" xml:lang="de">
              <quote>herrschen über</quote>
            </cit>
            <cit type="translation" xml:lang="en">
              <quote>rule over</quote>
            </cit>
            <cit type="translation" xml:lang="fr">
              <quote>régner sur</quote>
            </cit>
            <cit>
              <bibl>KoptHWb 10</bibl>
            </cit>
          </sense>
        </entry>

Maybe we corrected it after we delivered the files? Anyway if you corrected it, this can be closed

**Comment by amir-zeldes** [comment] 2016-10-27 19:21
oh, ok, it must have been an old version.

**Closed by amir-zeldes** 2016-10-27 19:21 UTC
Labels: bug
